### ISSUE TITLE
Accessing or Creating database in a docker CosmosDb Emulator with the .NET SDK hangs, no exception

### ISSUE THREAD

**Issue by diegosasw** [Azure/azure-cosmos-db-emulator-docker#101]
Image version: b05a7af77243
.NET CosmosDB version 3.41.0

**Describe the bug**
Unable to create or read databases using the SDK and CosmosDb emulator by following steps at
https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator?tabs=docker-linux%2Ccsharp&pivots=api-nosql

**To Reproduce**
This repo reproduces it https://github.com/diegosasw/cosmosdb-sample/tree/77d18b9b1861201b5e51003825540795ca37a7d7

1. Spin up a CosmosDb emulator docker container
```
docker run \
    --publish 8081:8081 \
    --publish 10250-10255:10250-10255 \
    --name linux-cosmosdb-emulator \
    --detach \
    mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
```
2. Download the certificate from the container
```
curl -k https://localhost:8081/_explorer/emulator.pem > emulatorcert.crt
```
3. Install the certificate (with elevated permissions) in the TRCA and make sure the UI is ready at the https url
```
certutil.exe -addstore root emulatorcert.crt
``` 
4. Clone .NET 8 console repo and run. See how it hangs. No exceptions, nothing.
```
git clone https://github.com/diegosasw/cosmosdb-sample.git
cd cosmosdb-sample
dotnet run --project src/CosmosDbSample
```

**Expected behavior**
It should create the database, be able to read it, or at least throw an exception informing on why it can't.

**Actual behavior**
It hangs, no error, nothing.

**Environment summary**
SDK Version: .NET 8
OS Version (e.g. Windows, Linux, MacOSX): Windows 11

**Additional context**
More info at the above sample repository where, also, bypassing SSL check in SDK does not make any difference. 

Is there **any** basic .NET app using this SDK and interacting with CosmosDb docker emulator?

I am new to CosmosDb and, after reading Microsoft documentation, I am unable to run a simple console app using the docker emulator. The documentation doesn't mention any limitation so I'm probably doing something wrong?

**Comment by niteshvijay1995** [comment]
In Step 1, try specifying the IP Address override. 
```
docker run \
    --publish 8081:8081 \
    --publish 10250-10255:10250-10255 \
    --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=172.0.0.1 \
    --name linux-cosmosdb-emulator \
    --detach \
    mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest```

**Comment by sajeetharan** [comment]
@diegosasw did the suggestion help?

**Comment by diegosasw** [comment]
@sajeetharan indeed, thanks for that.
