### ISSUE TITLE
Cosmos emulator admin panel fails to read items with hierarchical partition key

### ISSUE THREAD

**Issue by xperiandri** [Azure/azure-cosmos-db-emulator-docker#102]
**Describe the bug**
If you write an item that has an incomplete hierarchical partition key and then click on it in the admin panel to view it, an error will appear in the bottom output.

**To Reproduce**
1. Create an entity that has `id`, `TenantId` properties
2. Create a container with
``` F#
    static member CreateContainerIfNotExists (cosmosClient : CosmosClient) : Task = task {
        let database = cosmosClient.GetDatabase options.DatabaseName
        let! _ =
            let partitionKeys = [ "/TenantId"; "/UserId" ]
            let containerProperties = ContainerProperties ("ContainerName", partitionKeys)
            database.CreateContainerIfNotExistsAsync containerProperties
        ()
    }
```
4. Store an object from step 1
5. Open the admin panel and click on the item
6. No tab opes, error appears in the bottom

**Expected behavior**
Item content is opened in the tab

**Desktop:**
 - OS: Windows 11 (10.0.22631.3672)
 - Browser: Edge

**Additional context**
I used installed on Windows emulator

**Comment by sajeetharan** [comment]
Hi @xperiandri This is not related to emulator, can you please create a support ticket on azure portal?
