### ISSUE TITLE
HTTP 401 errors starting with version 2.14.20.0 (728f9251)

### ISSUE THREAD

**Issue by zthurston** [Azure/azure-cosmos-db-emulator-docker#105]
**Describe the bug**
Our integration test suite that uses Cosmos Emulator is failing with several different Cosmos errors when run against the new version of the Cosmos Emulator linux Docker image that was released yesterday.

Examples of errors:

```
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: Unauthorized (401); Substatus: 0; ActivityId: 0a60a3dc-ab14-4655-baae-7f5df2325308; Reason: (Message: {"Errors":["The MAC signature found in the HTTP request is not the same as the computed signature. Server used following string to sign - 'post\ndocs\ndbs\/shared.tests\/colls\/disposable_ac087b37-4775-4a1d-8668-3effb4af79da\nfri, 20 sep 2024 16:21:52 gmt\n\n'. Learn more: https:\/\/[aka.ms](http://aka.ms/)\/cosmosdb-tsg-mac-signature"]}
```
```
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: ServiceUnavailable (503); Substatus: 1007; ActivityId: e333de1f-7cd2-4faa-a85e-45a369291652; Reason: (Sorry, we are currently experiencing high demand in this region South Central US, and cannot fulfill your request at this time Thu, 19 Sep 2024 21:41:29 GMT.
```
```    
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: RequestTimeout (408); Substatus: 0; ActivityId: 0e7716a4-c259-4896-bba2-62d561673836; Reason: (GatewayStoreClient Request Timeout. Start Time UTC:9/20/2024 9:03:58 PM; Total Duration:65015.4088 Ms; Request Timeout 65000 Ms; Http Client Timeout:65000 Ms; Activity id: 0e7716a4-c259-4896-bba2-62d561673836;);; Diagnostics:{"Summary":{"GatewayCalls":{"(404, 0)":1,"(0, 0)":1}},"name":"CreateContainerIfNotExistsAsync"
```
```
Failed to cleanup database 59dc6af2-4d36-4435-9048-1f5cf96c312c: Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 861b292b-2676-415b-a31a-e957c267aacb; Reason: (
       code : NotFound
[[xUnit.net](http://xunit.net/) 00:01:14.47]         message : Message: {"Errors":["Resource Not Found. Learn more: https:\/\/[aka.ms](http://aka.ms/)\/cosmosdb-tsg-not-found"]}
```

**To Reproduce**
Inside of each test, we use a XUnit IAsyncLifetime and IClassFixture to create a new database and container with a guid in the name to isolate each test, using the .NET CosmosDB SDK's `CreateDatabaseIfNotExistsAsync()` and `CreateContainerIfNotExistsAsync()` methods. After the test executes, the test calls `DeleteContainerAsync()`. We use ConnectionMode.Gateway.

A sample test uses `CreateItemAsync()` and `ReadItemAsync()` to roundtrip a document to prove the container is working. 

I am reasonably certain that our tests aren't doing anything strange that would be causing the emulator to crash. The same tests pass when against the windows installer release of the emulator.

**Expected behavior**
Tests pass without errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Docker Images Used:**

 - Linux: 2.14.20.0 (728f9251)

**Arguments && Environment variables to start Docker:**
`docker run --publish 8081:8081 --publish 10250-10255:10250-10255 --name={name generated by GitHub actions} --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5 -d mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest`
 
**Docker Environment**
- Standalone, running inside of a container Github Actions self hosted runner.
 
**Additional context**
Same tests run without issue on the current version of the Windows Cosmos Emulator.
When run against a version of the linux docker image from May 21, 2024, the same tests pass.

As mentioned by others in these issues, it's frustrating to work with the Cosmos Emulator when there's no published version information on the docker images themselves and when working versions have the 180 day deactivation switch. We can't just stay on a working version because of this while either the bugs in our tests or the emulator are resolved.

**Comment by zthurston** [comment]
To see if it makes a difference, I ran our tests using `ConnectionMode.Direct`. I still get the tests erroring out, but with different errors this time:

`InitializeCosmosAsync_CreatesContainer" attempt (2/3)
[[xUnit.net](http://xunit.net/) 00:07:53.78]       Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: RequestTimeout (408); Substatus: 0; ActivityId: 92464187-4234-409f-829b-04c6b8b72021; Reason: (GatewayStoreClient Request Timeout. Start Time UTC:09/20/2024 21:33:37; Total Duration:65001.4157 Ms; Request Timeout 65000 Ms; Http Client Timeout:65000 Ms; Activity id: 92464187-4234-409f-829b-04c6b8b72021;);; Diagnostics:{"Summary":{"GatewayCalls":{"(404, 0)":1,"(0, 0)":1}},"name":"CreateContainerIfNotExistsAsync","start datetime":"2024-09-20T21:33:37.710Z","duration in milliseconds":65005.8778,"data":{"Client Configuration":{"Client Created Time Utc":"2024-09-20T21:33:37.6596018Z","MachineId":"vmId:841c9494-2d8d-4c06-9fb7-e118d036a252","VM Region":"eastus2","NumberOfClientsCreated":18,"NumberOfActiveClients":18,"ConnectionMode":"Gateway","User Agent":"cosmos-netstandard-sdk/3.37.1|10|X64|Ubuntu 22.04.4 LTS|.NET 8.0.6|DN|F 00000010|","ConnectionConfig":{"gw":"(cps:50, urto:6, p:False, httpf: True)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:True, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: )","ProcessorCount":4}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","duration in milliseconds":3.8892,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","duration in milliseconds":3.8763,"data":{"System Info":{"systemHistory":[{"dateUtc":"2024-09-20T21:32:40.6389337Z","cpu":5.632,"memory":10697068.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0328,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:32:50.6391566Z","cpu":4.704,"memory":10696516.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0349,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:33:00.6396068Z","cpu":4.704,"memory":10692268.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.048,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:33:10.6398466Z","cpu":4.145,"memory":10691816.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0333,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:33:20.6444421Z","cpu":5.458,"memory":10691828.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0344,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:33:30.6446848Z","cpu":4.869,"memory":10688576.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0392,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TelemetryHandler","duration in milliseconds":3.8727,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","duration in milliseconds":3.8706,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","duration in milliseconds":3.8586,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","duration in milliseconds":3.8567,"children":[{"name":"Microsoft.Azure.Cosmos.GatewayStoreModel Transport Request","duration in milliseconds":3.8264,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2024-09-20T21:33:37.7102221Z","DurationInMs":3.4639,"RequestUri":"https://localhost:8081/dbs/2e097872-ffd6-4758-8f87-db4b1ca56aa5/colls/ledger-73252395-d977-4b9f-bea3-4b3557cfc0ff","ResourceType":"Collection","HttpMethod":"GET","ActivityId":"92464187-4234-409f-829b-04c6b8b72021","StatusCode":"NotFound","ReasonPhrase":"Not Found"}]},"PointOperationStatisticsTraceDatum":{"Id":"PointOperationStatistics","ActivityId":"92464187-4234-409f-829b-04c6b8b72021","ResponseTimeUtc":"2024-09-20T21:33:37.7139293Z","StatusCode":404,"SubStatusCode":0,"RequestCharge":2,"RequestUri":"dbs/2e097872-ffd6-4758-8f87-db4b1ca56aa5/colls/ledger-73252395-d977-4b9f-bea3-4b3557cfc0ff","ErrorMessage":null,"RequestSessionToken":null,"ResponseSessionToken":"0:-1#27","BELatencyInMs":"0.199"}}}]}]}]}]}]}]},{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","duration in milliseconds":65001.7795,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","duration in milliseconds":65001.7592,"data":{"System Info":{"systemHistory":[{"dateUtc":"2024-09-20T21:33:50.6451415Z","cpu":5.173,"memory":10688616.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0313,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:34:00.6454048Z","cpu":4.853,"memory":10687120.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0391,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:34:10.6456565Z","cpu":4.816,"memory":10686152.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0341,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:34:20.6459158Z","cpu":4.971,"memory":10685916.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0334,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:34:30.6461364Z","cpu":4.588,"memory":10684904.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0325,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3},{"dateUtc":"2024-09-20T21:34:40.6463663Z","cpu":4.443,"memory":10684160.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0308,"availableThreads":32765,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":3}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TelemetryHandler","duration in milliseconds":65001.7525,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","duration in milliseconds":65001.7495,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","duration in milliseconds":65001.5815,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","duration in milliseconds":65001.5794,"children":[{"name":"Microsoft.Azure.Cosmos.GatewayStoreModel Transport Request","duration in milliseconds":65001.5168,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2024-09-20T21:33:37.7141707Z","DurationInMs":65001.3886,"RequestUri":"https://localhost:8081/dbs/2e097872-ffd6-4758-8f87-db4b1ca56aa5/colls","ResourceType":"Collection","HttpMethod":"POST","ActivityId":"92464187-4234-409f-829b-04c6b8b72021","ExceptionType":"System.Threading.Tasks.TaskCanceledException","ExceptionMessage":"The operation was canceled."}]}}}]}]}]}]}]}]}]}`

and

`InitializeCosmosAsync_DoesNothingWhenAccountKeyIsNull [PASS]
[[xUnit.net](http://xunit.net/) 00:05:43.32]       Output:
[[xUnit.net](http://xunit.net/) 00:05:43.32]         Failed to cleanup database 86efafa9-1a7d-431e-9184-14aac8776d4f: Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 89f93b5c-1266-406b-af6b-7ec3ff17c6cf; Reason: (
[[xUnit.net](http://xunit.net/) 00:05:43.32]         code : NotFound
[[xUnit.net](http://xunit.net/) 00:05:43.32]         message : Message: {"Errors":["Resource Not Found. Learn more: https:\/\/[aka.ms](http://aka.ms/)\/cosmosdb-tsg-not-found"]}
[[xUnit.net](http://xunit.net/) 00:05:43.32]         ActivityId: 89f93b5c-1266-406b-af6b-7ec3ff17c6cf, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: 
[[xUnit.net](http://xunit.net/) 00:05:43.32]         RequestStartTime: 2024-09-20T21:32:32.3536183Z, RequestEndTime: 2024-09-20T21:32:32.3576969Z,  Number of regions attempted:1
[[xUnit.net](http://xunit.net/) 00:05:43.32] AsyncTaskBroker.Shared.Tests: Test "AsyncTaskBroker.Shared.Tests.ServiceProviderExtensionsTests.InitializeCosmosAsync_CreatesContainerWhenDatabaseExists" failed but is set to retry (1/3) . . .
[[xUnit.net](http://xunit.net/) 00:05:43.32]         {"systemHistory":[{"dateUtc":"2024-09-20T21:31:39.8254882Z","cpu":100.000,"memory":10736492.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0975,"availableThreads":32766,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":2},{"dateUtc":"2024-09-20T21:31:49.8263967Z","cpu":100.000,"memory":10735336.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.1568,"availableThreads":32766,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":2},{"dateUtc":"2024-09-20T21:31:59.8281367Z","cpu":100.000,"memory":10727328.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0656,"availableThreads":32766,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":2},{"dateUtc":"2024-09-20T21:32:09.8259267Z","cpu":100.000,"memory":10737924.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0634,"availableThreads":32766,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":2},{"dateUtc":"2024-09-20T21:32:19.8274810Z","cpu":100.000,"memory":10733944.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0648,"availableThreads":32766,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":2},{"dateUtc":"2024-09-20T21:32:29.8267071Z","cpu":100.000,"memory":10710332.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0674,"availableThreads":32766,"minThreads":4,"maxThreads":32767},"numberOfOpenTcpConnection":2}]}
[[xUnit.net](http://xunit.net/) 00:05:43.32] AsyncTaskBroker.Shared.Tests: Running test "AsyncTaskBroker.Shared.Tests.ServiceProviderExtensionsTests.InitializeCosmosAsync_CreatesContainerWhenDatabaseExists" attempt (2/3)
[[xUnit.net](http://xunit.net/) 00:05:43.32]         RequestStart: 2024-09-20T21:32:32.3536183Z; ResponseTime: 2024-09-20T21:32:32.3536183Z; StoreResult: StorePhysicalAddress: rntbd://172.17.0.2:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 21, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#21, UsingLocalLSN: False, TransportException: null, BELatencyMs: 0.151, ActivityId: 89f93b5c-1266-406b-af6b-7ec3ff17c6cf, RetryAfterInMs: , ReplicaHealthStatuses: [(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32)], TransportRequestTimeline: {"requestTimeline":[{"event": "Created", "startTimeUtc": "2024-09-20T21:32:32.3536183Z", "durationInMs": 0.0117},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2024-09-20T21:32:32.3536300Z", "durationInMs": 0.0014},{"event": "Pipelined", "startTimeUtc": "2024-09-20T21:32:32.3536314Z", "durationInMs": 0.0583},{"event": "Transit Time", "startTimeUtc": "2024-09-20T21:32:32.3536897Z", "durationInMs": 0.4744},{"event": "Received", "startTimeUtc": "2024-09-20T21:32:32.3541641Z", "durationInMs": 0.0715},{"event": "Completed", "startTimeUtc": "2024-09-20T21:32:32.3542356Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"False","callsPendingReceive":0,"lastSendAttempt":"2024-09-20T21:32:32.3413767Z","lastSend":"2024-09-20T21:32:32.3413767Z","lastReceive":"2024-09-20T21:32:32.3454627Z"},"requestSizeInBytes":487,"responseMetadataSizeInBytes":171,"responseBodySizeInBytes":87};
[[xUnit.net](http://xunit.net/) 00:05:43.32]          ResourceType: Database, OperationType: Read
[[xUnit.net](http://xunit.net/) 00:05:43.32]         RequestStart: 2024-09-20T21:32:32.3536183Z; ResponseTime: 2024-09-20T21:32:32.3576969Z; StoreResult: StorePhysicalAddress: rntbd://172.17.0.2:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 21, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#21, UsingLocalLSN: False, TransportException: null, BELatencyMs: 0.139, ActivityId: 89f93b5c-1266-406b-af6b-7ec3ff17c6cf, RetryAfterInMs: , ReplicaHealthStatuses: [(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32),(port: 10251 | status: Unknown | lkt: 09/20/2024 21:32:32)], TransportRequestTimeline: {"requestTimeline":[{"event": "Created", "startTimeUtc": "2024-09-20T21:32:32.3536183Z", "durationInMs": 0.0051},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2024-09-20T21:32:32.3536234Z", "durationInMs": 0.0007},{"event": "Pipelined", "startTimeUtc": "2024-09-20T21:32:32.3536241Z", "durationInMs": 0.0282},{"event": "Transit Time", "startTimeUtc": "2024-09-20T21:32:32.3536523Z", "durationInMs": 0.8003},{"event": "Received", "startTimeUtc": "2024-09-20T21:32:32.3544526Z", "durationInMs": 0.0612},{"event": "Completed", "startTimeUtc": "2024-09-20T21:32:32.3545138Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":2,"openConnections":1},"connectionStats":{"waitforConnectionInit":"False","callsPendingReceive":1,"lastSendAttempt":"2024-09-20T21:32:32.3536183Z","lastSend":"2024-09-20T21:32:32.3536183Z","lastReceive":"2024-09-20T21:32:32.3454627Z"},"requestSizeInBytes":487,"responseMetadataSizeInBytes":171,"responseBodySizeInBytes":87};
[[xUnit.net](http://xunit.net/) 00:05:43.32]          ResourceType: Database, OperationType: Read
[[xUnit.net](http://xunit.net/) 00:05:43.32]         , SDK: Microsoft.Azure.Documents.Common/2.14.0
[[xUnit.net](http://xunit.net/) 00:05:43.32]         );`

**Comment by niteshvijay1995** [comment]
> **Describe the bug** Our integration test suite that uses Cosmos Emulator is failing with several different Cosmos errors when run against the new version of the Cosmos Emulator linux Docker image that was released yesterday.
> 
> Examples of errors:
> 
> ```
> Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: Unauthorized (401); Substatus: 0; ActivityId: 0a60a3dc-ab14-4655-baae-7f5df2325308; Reason: (Message: {"Errors":["The MAC signature found in the HTTP request is not the same as the computed signature. Server used following string to sign - 'post\ndocs\ndbs\/shared.tests\/colls\/disposable_ac087b37-4775-4a1d-8668-3effb4af79da\nfri, 20 sep 2024 16:21:52 gmt\n\n'. Learn more: https:\/\/[aka.ms](http://aka.ms/)\/cosmosdb-tsg-mac-signature"]}
> ```
> 
> ```
> Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: ServiceUnavailable (503); Substatus: 1007; ActivityId: e333de1f-7cd2-4faa-a85e-45a369291652; Reason: (Sorry, we are currently experiencing high demand in this region South Central US, and cannot fulfill your request at this time Thu, 19 Sep 2024 21:41:29 GMT.
> ```
> 
> ```
> Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: RequestTimeout (408); Substatus: 0; ActivityId: 0e7716a4-c259-4896-bba2-62d561673836; Reason: (GatewayStoreClient Request Timeout. Start Time UTC:9/20/2024 9:03:58 PM; Total Duration:65015.4088 Ms; Request Timeout 65000 Ms; Http Client Timeout:65000 Ms; Activity id: 0e7716a4-c259-4896-bba2-62d561673836;);; Diagnostics:{"Summary":{"GatewayCalls":{"(404, 0)":1,"(0, 0)":1}},"name":"CreateContainerIfNotExistsAsync"
> ```
> 
> ```
> Failed to cleanup database 59dc6af2-4d36-4435-9048-1f5cf96c312c: Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 861b292b-2676-415b-a31a-e957c267aacb; Reason: (
>        code : NotFound
> [[xUnit.net](http://xunit.net/) 00:01:14.47]         message : Message: {"Errors":["Resource Not Found. Learn more: https:\/\/[aka.ms](http://aka.ms/)\/cosmosdb-tsg-not-found"]}
> ```
> 
> **To Reproduce** Inside of each test, we use a XUnit IAsyncLifetime and IClassFixture to create a new database and container with a guid in the name to isolate each test, using the .NET CosmosDB SDK's `CreateDatabaseIfNotExistsAsync()` and `CreateContainerIfNotExistsAsync()` methods. After the test executes, the test calls `DeleteContainerAsync()`. We use ConnectionMode.Gateway.
> 
> A sample test uses `CreateItemAsync()` and `ReadItemAsync()` to roundtrip a document to prove the container is working.
> 
> I am reasonably certain that our tests aren't doing anything strange that would be causing the emulator to crash. The same tests pass when against the windows installer release of the emulator.
> 
> **Expected behavior** Tests pass without errors.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> 
> **Docker Images Used:**
> 
> * Linux: 2.14.20.0 (728f9251)
> 
> **Arguments && Environment variables to start Docker:** `docker run --publish 8081:8081 --publish 10250-10255:10250-10255 --name={name generated by GitHub actions} --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5 -d mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest`
> 
> **Docker Environment**
> 
> * Standalone, running inside of a container Github Actions self hosted runner.
>    
>   **Additional context**
>   Same tests run without issue on the current version of the Windows Cosmos Emulator.
>   When run against a version of the linux docker image from May 21, 2024, the same tests pass.
> 
> As mentioned by others in these issues, it's frustrating to work with the Cosmos Emulator when there's no published version information on the docker images themselves and when working versions have the 180 day deactivation switch. We can't just stay on a working version because of this while either the bugs in our tests or the emulator are resolved.

Can you try running emulator by passing IP address override?
`docker run --publish 8081:8081 --publish 10250-10255:10250-10255 --name={name generated by GitHub actions} --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5 --env  AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 -d mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest`

In the meantime, I will check what is going wrong

**Comment by zthurston** [comment]
> Can you try running emulator by passing IP address override? `docker run --publish 8081:8081 --publish 10250-10255:10250-10255 --name={name generated by GitHub actions} --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5 --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 -d mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest`
> 
> In the meantime, I will check what is going wrong

We tried changing the `AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE` field and didn't notice a difference in the errors.

I noticed there's a stable image tag now (https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/106#issuecomment-2367732719), we changed our tests to use this image and our tests work against this version without these errors. We are seeing occasional timeout related errors, but I think those are due to our runners being slow.

Thank you for your prompt response and for pushing a stable image tag!

**Comment by niteshvijay1995** [comment]
@zthurston Thanks for confirming that stable version worked for you. 
We have fixed the issue in `latest` tagged version as well. You can take a fresh pull of image.

**Comment by zthurston** [comment]
> @zthurston Thanks for confirming that stable version worked for you. We have fixed the issue in `latest` tagged version as well. You can take a fresh pull of image. Version - `2.14.20.0 (dd7750b6)`

I have ran our tests against `latest`, `2.14.20.0 (dd7750b6)` and they pass with that version as well, so confirmed from my side.

Thank you again!
