### ISSUE TITLE
CreateIfNotExists failing after latest version 2.14.20.0

### ISSUE THREAD

**Issue by shreyanshchordia** [Azure/azure-cosmos-db-emulator-docker#106]
**Describe the bug**
Our end to end tests have started failing with the latest image of cosmosdb docker emulator. Example error that we are seeing:

`Message: {"Errors":["Resource with specified id, name, or unique index already exists."]}`

The above error is thrown from containers.createIfNotExists function. We see this error even on empty fresh set up databases. 

**To Reproduce**
1. Pull the latest image of the emulator
2. Start a container with the image and setup the databases. 
3. Run containers.createIfNotExists function to create your containers in the database. 

**Expected behavior**
End to end tests must pass. containers.createIfNotExists function should not throw an error if the container exists. 
**Screenshots**
![image](https://github.com/user-attachments/assets/c3c4c0b9-44d8-407c-bd75-3a4cc045310d)

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - E2E tests failing on local (Windows 11), as well as pipeline agents (Linux) with the above mentioned error.

**Docker Images Used: **
 - Linux

**Arguments && Environment variables to start Docker:
 `docker run -d --publish 8081:8081 \
    --publish 10250-10255:10250-10255 \
    --interactive \
    --tty \
    --name e2e-emulator \
    --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=32 \
    mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest`

**Docker Environment**
 - Standalone

**Comment by niteshvijay1995** [comment]
@shreyanshchordia We are investigating the issue with latest version. In the meantime you can pull the stable version of emulator from `mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:stable`

**Comment by aanaji** [comment]
Thanks @niteshvijay1995. This worked for me too!!

@sajeetharan, I can't find the Cosmos DB emulator in the Microsoft Artifact Registry. Could someone from Microsoft start publishing the Cosmos DB emulator details there? 

https://mcr.microsoft.com/en-us/

**Comment by sajeetharan** [comment]
@aanaji yes it has been feedback from many customers, however we have not prioritized this ask for the moment. We will be working on this soon and keep you posted!

**Comment by davidwalschots** [comment]
@aanaji One can run the following commands to get the information, even when not listed in the portal:

To list all the images found in the catalog:

```bash
curl -X GET https://mcr.microsoft.com/v2/_catalog
```

To list all the image versions of `cosmosdb/linux/azure-cosmos-emulator`:

```bash
curl -X GET https://mcr.microsoft.com/v2/cosmosdb/linux/azure-cosmos-emulator/tags/list
```

For us, using `stable` did not make a difference. We reverted back to `2.14.18-e2d1bbf7`.

**Comment by niteshvijay1995** [comment]
This issue is fixed in the latest version of emulator. 
Version - `2.14.20.0 (dd7750b6)` - Available on `latest` tag
