### ISSUE TITLE
"mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:mongodb" is expired

### ISSUE THREAD

**Issue by ry0y4n** [Azure/azure-cosmos-db-emulator-docker#112]
Today, I pulled the image "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:~latest~mongodb", and encoutered the following error when run it:

```
Error: The evaluation period has expired.
./cosmosdb-emulator: ERROR: PAL initialization failed. Error: 104
```

I found issue #60, and it seem to be related to this problem. This image was created "2024-04-23T04:12:07.234951457Z", and since 180 days have passed, I believe this is cause of the issue.
Could you please update the image and publish a new version?

**Comment by niteshvijay1995** [comment]
A new version is already pushed to latest tag. Please checkin old image is cached at your end. 
Try removing the image on your workstation and pull again.

**Comment by ry0y4n** [comment]
Hi @niteshvijay1995 ,
Thank you for the quick response.

I have a question: What is the purpose of the `mongodb` tag image? I’m unsure whether I should use the `latest` tag or the `mongodb` tag moving forward.

Could you clarify this for me?

**Comment by ry0y4n** [comment]
@niteshvijay1995 Ah, I realized the title and description of the issue were incorrect. The image I used wasn’t the latest tag, but the mongodb tag, and that’s the one that had expired.

**Comment by niteshvijay1995** [comment]
You can use the latest tagged image for mongo as well.

**Comment by ry0y4n** [comment]
@niteshvijay1995 Thanks, I'll use latest tagged iamge.

Just to make sure I understand correctly—if the `latest` tag can also be used for mongo, what is the purpose of having a separate `mongodb` tag? Am I misunderstanding something about their distinction or usage?

**Comment by radovanradic** [comment]
I just deleted and pulled mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:mongodb image and I am getting expiration error because the image is 6 months old:
>
mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator                   mongodb                       94581d68a4f3   6 months ago    2.27GB

How can we get the new version that won't throw expiration error?

**Comment by niteshvijay1995** [comment]
> I just deleted and pulled mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:mongodb image and I am getting expiration error because the image is 6 months old:
> >
> mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator                   mongodb                       94581d68a4f3   6 months ago    2.27GB
> 
> How can we get the new version that won't throw expiration error?

Please use latest tag instead of mongodb.

**Comment by radovanradic** [comment]
I need mongo, `mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest` is not working on Mac Silicon for me (on Colima or Rancher Desktop).

**Comment by radovanradic** [comment]
Last time I was working with mongodb tag I did not have issues. Now, I am using the emulator (latest) with testcontainers `CosmosDBEmulatorContainer` and now have waiting strategy that works, container starts up but after some operations it crashes.
I see this logged
```
This program has encountered a fatal error and cannot continue running at Fri Nov  8 09:55:15 2024
The following diagnostic information is available:

         Reason: OS Hard Error (0x00000002)
    Stack Trace:
                 file://package1/windows/system32/sqlpal.dll+0x0000000000209C12
                 file://package1/windows/system32/sqlpal.dll+0x0000000000208D23
                 file://package1/windows/system32/sqlpal.dll+0x000000000023D371
                 file://package1/windows/system32/sqlpal.dll+0x0000000000201F6E
                 file://package1/windows/system32/sqlpal.dll+0x00000000003A03BB
                 file:///windows/system32/ntdll.dll+0x00000000000F8B1F
                 file:///Windows/SYSTEM32/KERNELBASE.dll+0x0000000000102688
                 file:///Packages/ServerService/ServerService.Code/Microsoft.Azure.Cosmos.Server.exe+0x0000000001624F61
                 file:///Packages/ServerService/ServerService.Code/Microsoft.Azure.Cosmos.Server.exe+0x0000000001625002
                 file:///Windows/SYSTEM32/KERNELBASE.dll+0x0000000000087B6C
                 file:///windows/system32/ntdll.dll+0x00000000000DB3F7
                 file:///windows/system32/ntdll.dll+0x00000000000FF526
                 file:///windows/system32/ntdll.dll+0x00000000000E6F06
                 file:///windows/system32/ntdll.dll+0x00000000000F5B06
                 file:///windows/system32/ntdll.dll+0x00000000000FAF8F
                 file:///windows/system32/ntdll.dll+0x000000000009B4B6
                 file:///windows/system32/ntdll.dll+0x00000000000F9CDE
                 file:///Packages/ServerService/ServerService.Code/Microsoft.Azure.Cosmos.Server.exe+0x0000000002CB527C
        Process: 21 - cosmosdb-emulator
         Thread: 141 (application thread 0x1fc)
    Instance Id: 68bd7acd-7aeb-4126-bccd-42b40756fd8d
       Crash Id: d1f6a23d-ea16-42d8-829d-641732a09719
    Build stamp: (null)
   Distribution: Ubuntu 22.04.5 LTS
     Processors: 4
   Total Memory: 16789360640 bytes
      Timestamp: Fri Nov  8 09:55:15 2024
     Last errno: -34938881
Last errno text: Unknown error -34938881
Capturing a dump of 21

```
Apologies @ry0y4n for hijacking your issue.

**Comment by niteshvijay1995** [comment]
Please share the generated dump file. I will try to debug it.

**Comment by abhijitpai** [comment]
This issue is about the mongodb tag, suggestion is to use the latest tag including for Mongo usage; closing this as we need to track other issues separately.
