### ISSUE TITLE
Need JOINS, ARRAY_CONTAINS() and LENGTH() in new #cosmosEmulatorVnextPreview

### ISSUE THREAD

**Issue by snext-twilde** [Azure/azure-cosmos-db-emulator-docker#116]
Hey Microsoft-Team,

great to have cosmosdb emulator finally working on Apple silicon, thank you very much. Although I cannot use it, because I need ARRAY_CONTAINS(), JOINS and LENGTH() to be working. Could work around LENGTH(), but no way for ARRAY_CONTAINS. 

#cosmosEmulatorVnextPreview

Best,
Thomas

**Comment by DmitriMelnikov** [comment]
@snext-twilde can we have a separate issues for ARRAY_CONTAINS(), JOINS and LENGTH() ?

I plan to start working on adding ARRAY_CONTAINS

**Comment by snext-twilde** [comment]
sure :-)
