### ISSUE TITLE
Cannot get SSL certificate from linux preview emulator

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [Azure/azure-cosmos-db-emulator-docker#121]
**Describe the bug**
Following the instructions for downloading the SSL certificate in the [README](https://github.com/Azure/azure-cosmos-db-emulator-docker?tab=readme-ov-file#installing-certificates-for-java-sdk) I get an error about wrong version number.

**To Reproduce**
1. Follow the [README](https://github.com/Azure/azure-cosmos-db-emulator-docker?tab=readme-ov-file#linux-based-emulator-preview) for installing and running the linux preview emulator
2. Run the [code](https://github.com/Azure/azure-cosmos-db-emulator-docker?tab=readme-ov-file#linux-based-emulator-preview) provided for getting the SSL certificate.

**Expected behavior**
The SSL certificate is downloaded.

**Actual behavior**
You get an error:

```
$ openssl s_client -connect ${EMULATOR_HOST}:${EMULATOR_PORT} </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $EMULATOR_CERT_PATH
4067F2F182750000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354:
```

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 24.04.1 LTS)

**Docker Images Used:**
 - Linux: `mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview`

**Arguments && Environment variables to start Docker:**

docker run --detach --publish 8081:8081 --publish 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview

**Comment by xgerman** [comment]
The new emulator will generate a new certificate when starting up. To get access to it run the following:

```
containerId = docker ps --all --quiet --latest
docker cp ${containerId}:/scripts/certs/domain.crt .
docker cp ${containerId}:/scripts/certs/rootCA.crt .
```

You then can use `keytool` to add them to your keystore.

**Note:** You will need to do those steps every time you start the emulator. To avoid this you can eitehr use http (which is the default and will be fully supported in upcoming Java SDK version) or specify your own certificates.

**Comment by xgerman** [comment]
@Blackbaud-JasonBodnar  wonder if that solved your issue.

**Comment by kmandalas** [comment]
@xgerman please take into consideration my comment here: https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/117#issuecomment-2495656578

**Comment by xgerman** [comment]
Yes, we are planning to address that in the January 2025 release.

**Comment by akoufa** [comment]
@xgerman When is the plan to release the Java SDK that can use http?
