### ISSUE TITLE
ORDER BY breaks when some documents do not have property defined #cosmosEmulatorVnextPreview

### ISSUE THREAD

**Issue by jvalkeejarvi** [Azure/azure-cosmos-db-emulator-docker#123]
**Describe the bug**
Error is returned when some documents are missing the property that is used for ordering.

**To Reproduce**

Add following documents to container:
```json
[
    {
        "id": "1",
        "_ts": 1732136483,
        "desc": "desc1",
        "name": "name1",
        "_etag": "1d314a8c-1e7c-48e5-aef1-d3eaba949570",
        "partitionKey": "part"
    },
    {
        "id": "2",
        "_ts": 1732136497,
        "desc": "desc1",
        "name": "name1",
        "_etag": "4eac0186-7bc0-40de-823b-2b113f961bfd",
        "partitionKey": "part"
    },
    {
        "id": "3",
        "_ts": 1732136505,
        "desc": "desc2",
        "name": "name2",
        "_etag": "bc79b6e0-5e30-4ca6-8c70-4bdbc76f0e35",
        "partitionKey": "part"
    },
    {
        "id": "4",
        "_ts": 1732137353,
        "desc": "desc3",
        "name": "name0",
        "_etag": "ff48f9ab-4240-435a-8b09-5ff7ddb51c30",
        "_self": "dbs/test/colls/cont/docs/4/",
        "partitionKey": "part"
    },
    {
        "id": "5",
        "_ts": 1732137407,
        "sub": {
            "name": "55"
        },
        "_etag": "1c6abee8-d872-40c4-bcef-2fc93a9e66ce",
        "partitionKey": "part2"
    }
]
```
Note that last document does not have property named `name` on top level.

Run following query:
```sql
SELECT * FROM c order by c.name
```

**Expected behavior**
Items are returned in correct order (document with name property missing is first).

**Comment by DmitriMelnikov** [comment]
Fix is checked in and will be available on the next release

**Comment by DmitriMelnikov** [comment]
The fix will be shipped in the post Nov27 release.

**Comment by DmitriMelnikov** [comment]
Our publish pipeline did not work until recently preventing the fixes from shipment. Pipeline is fixed now, and the fixes should be available. Please use ```docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview``` to donwload the latest image and ```docker inspect mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview``` to validate the latest build: Created field should be no less than 2024-12-16T20:25:13.18725592Z
