### ISSUE TITLE
Version for running on Mac or *nix

### ISSUE THREAD

**Issue by pwiebe** [Azure/azure-cosmos-db-emulator-docker#13]
Would really be nice to have a version that runs on a Mac.

**Comment by tudorian** [comment]
It would be a great addtion

**Comment by Cephei** [comment]
Would really love to see this as well.

**Comment by aztlan2k** [comment]
a container that runs on Linux (Ubuntu) would be great.

**Comment by lakindu95** [comment]
+1 for for a version which can run on macOS.

**Comment by andreacassioli** [comment]
This is a must to have.

**Comment by ddavtian** [comment]
+1

**Comment by drinkbird** [comment]
I'm surprised it doesn't work on linux already. I'm trying to demonstrate xplat development with .net core on linux with Cosmos and docker compose, and this is a blocker.

**Comment by gabrieljoelc** [comment]
If [this feedback answer](https://feedback.azure.com/forums/217298-storage/suggestions/7048446-provide-storage-emulation-for-mac-and-linux) is any indication, there's a good chance we're getting this...

**Comment by mossyblog** [comment]
+1 for a version on OSX....

**Comment by pradeep-pioneer** [comment]
👍 +1

**Comment by frantisekjandos** [comment]
+1

**Comment by driftingPixel** [comment]
+1

**Comment by alexjamesbrown** [comment]
As an interim solution, does anyone have a guide on how to connect to a Cosmos Emulator, running on a Windows VM, from a Mac host?

**Comment by ukiuni** [comment]
+1

**Comment by peterseale-tethr-com** [comment]
From the feedback page: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/18533509-add-documentdb-emulator-support-for-mac-os-x-and

> June 24, 2019
> Just a quick update. Work on this feature continues but is taking longer than expected.
> 
> We have recently published guidance how how users who can run Windows in a VM whether on Parallels or Virtual Box with a Mac or Linux host can use the Cosmos emulator. Please feel free to use this as a workaround.
> https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#running-on-mac-or-linux
> 
> When this feature is complete we will update here.
> 
> Thank you.

I am also eagerly awaiting this, along with the other 1700 votes. So you're not alone.

**Comment by dany74q** [comment]
+1 - Is this on the road map for 2020 ?

**Comment by natemccoy** [comment]
COVID got it, no *nix 4 u

**Comment by DavidHanover** [comment]
Also blocked rn because of this, we're going to have to find a workaround for now

**Comment by kelong** [comment]
Is anything going here?

**Comment by peterseale-tethr-com** [comment]
https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator

**Comment by sajeetharan** [comment]
Closing as duplicate https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/54
