### ISSUE TITLE
Need partial document updates via patch

### ISSUE THREAD

**Issue by kmandalas** [Azure/azure-cosmos-db-emulator-docker#134]
Need to be able to perform partial document updates utilizing the **Patch** operation. Example using Spring Boot:

```
CosmosPatchOperations patchOperations = CosmosPatchOperations.create().replace("/type", "USER_ACTION_Z");
demoAuditRepository.save(audits.get(0).getId(), new PartitionKey(audits.get(0).getPrincipal()), DemoAudit.class, patchOperations);
```

Sample project with integration tests: 

- https://github.com/kmandalas/cosmosdb-vnext
- [DemoAuditRepositoryIntegrationTest#testPartialUpdateViaPatch](https://github.com/kmandalas/cosmosdb-vnext/blob/edbd143a4afb62f04a616c9b29fb999f5c29130c/src/test/java/com/example/demo/audits/DemoAuditRepositoryIntegrationTest.java#L49)

Patch is not yet supported as mentioned in https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-linux#feature-support but would be nice to have updates here.

**Comment by xgerman** [comment]
We are planning to support patch very soon.

**Comment by kmandalas** [comment]
I have tested it today by pulling new image and patch works. Integration test (Java 17, Spring Boot) here: https://github.com/kmandalas/cosmosdb-vnext/blob/9ad95e048268593268853296e4ea1df73dc56b69/src/test/java/com/example/demo/audits/DemoAuditRepositoryIntegrationTest.java#L49

**Comment by xgerman** [comment]
Thank you for confirming.
