### ISSUE TITLE
Linux Image

### ISSUE THREAD

**Issue by garfbradaz** [Azure/azure-cosmos-db-emulator-docker#17]
any chance a Linux Image could be added to the backlog?

I have a Raspberry Pi Cluster and would love to run it on there.

**Comment by RohanNagar** [comment]
Any updates on this?

**Comment by renato04** [comment]
Any updates on this?

**Comment by dasjestyr** [comment]
Becoming increasingly problematic for modern development particularly when you're trying to develop hundreds of microservices on a mac. It's aggravating not being able to spin up a test instance in docker. Instead I have to go through the pain of getting that stuff set up correctly in Azure with all the naming conventions and such, burning more time and money.

**Comment by syedhassaanahmed** [comment]
+1 Any ETA on this?

**Comment by garfbradaz** [comment]
Upvote here guys:

https://feedback.azure.com/forums/263030/suggestions/18533509

**Comment by newtack** [comment]
Looking for the same, any updated plans to support Linux?

**Comment by newtack** [comment]
The problem for us at this point is not for development in our case (we use Windows) but for CI/CD which runs on Docker (Linux). Can someone from Azure team comment on this?

**Comment by rubit0** [comment]
No news? I honestly would be totally fine with a very crude emulator, heck it could be even based on MongoDb or something.

**Comment by RohanNagar** [comment]
Looks like work on this has started today: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/18533509-add-documentdb-emulator-support-for-mac-os-x-and?tracking_code=eddebf28300fe85b25cf5f9e73541e0b

**Comment by jpbochi** [comment]
while there is no official emulator, does anyone know of any alternatives? Perhaps even some partial implementation.

**Comment by dnwarnock** [comment]
You can just spin up a paired down test instance on Azure. I believe there is a free (or nearly free) tier available.

**Comment by jpbochi** [comment]
> You can just spin up a paired down test instance on Azure. I believe there is a free (or nearly free) tier available.

I'd like to avoid that. Obviously, it has lots of drawbacks, or a local DB would not even exist. Anyway, I'll have to investigate if that is a workable solution for my case. Thanks.

**Comment by dnwarnock** [comment]
What's your use case? Obviously it's difficult to provide an ideal solution with such a small amount of information.

**Comment by nkzawa** [comment]
Hello, we just made a mock server implementation public. Hope it will be helpful for testing your applications.

https://github.com/zeit/cosmosdb-server

**Comment by dany74q** [comment]
+1 - Is this on the road map for 2020 ?

**Comment by softdev87** [comment]
Is this on the road map before 2025 ?

**Comment by JustinGrote** [comment]
Seems like the current plan is "go pound sand or use a live azure account".

CosmosDB does have a free tier available now, which helps, but it doesn't help for offline or air-gapped testing and development.

**Comment by evandropomatti** [comment]
> Upvote here guys:
> 
> https://feedback.azure.com/forums/263030/suggestions/18533509

Work started June 24, 2019. Go there and upvote.

**Comment by codematrix** [comment]
It would be nice to at least create a cert like so: **host.docker.internal** 

This way during local development, my Linux docker containers can at least hit **https://host.docker.internal:8081**  without complaining about "The SSL connection could not be established, see inner exception."

This would be a great plus.

**Comment by whung1** [comment]
@codematrix

To generate a cert, you can see this post where I talk about the steps
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1232#issuecomment-621422833

I would advise looking at the post later for updated scripts in case you want to automate this for your team.
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1232#issuecomment-632942023

**Comment by danielptm** [comment]
We need this. Our company is exploring using Mongodb atlas because they think it will in the grand scheme be cheaper because they will save on developer setup/troubleshooting time. If this were available for linux cosmos would have been the choice.

**Comment by D3MaxT** [comment]
Same problem. Windows 10 host, started a new app running in Docker Linux containers on WSL2. Wanted to try out Cosmos DB, so installed the emulator.

First run: "The remote certificate is invalid according to the validation procedure." error using https://host.docker.internal:8081 to connect.

Great development experience Microsoft. Just will have to use SQL again.

**Comment by ltwlf** [comment]
Linux docker is needed. We use MAC and windows, every dev can choose would he prefer. On widows we use WSL/2. I don’t like the cloud option even there is a free tier. I want to use the same docker dev flow that I always use.

**Comment by jabba2324** [comment]
Its Feb 2021 and still no linux docker container..

**Comment by thesqlpro** [comment]
docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

to get the linux based azure-cosmos-emulator

**Comment by lonewarrior556** [comment]
> @Azure Azure deleted a comment from thesqlpro 1 hour ago

What!?!?

**Comment by JustinGrote** [comment]
Seriously there was a comment from @thesqlpro that linked to (what I assume, did not test) was a linux docker container. Was that supposed to not be published yet? You're only going to Streisand effect it, I'm going to post it everywhere :P

**Comment by milismsft** [comment]
@JustinGrote the previous comment was published by mistake. Yes, we are currently working on adding Linux support for the Azure Cosmos DB emulator but we are in the very early stages of testing it out and by no means ready for the general public to try it out. 
Please continue to monitor Microsoft official channels and we hope to make an announcement on this relatively soon.

**Comment by JustinGrote** [comment]
@milismsft thanks for clarifying, it is appreciated.

**Comment by thesqlpro** [comment]
Apologies for the mistake.

**Comment by TheOddler** [comment]
> Please continue to monitor Microsoft official channels and we hope to make an announcement on this relatively soon.

Which official channels specifically? Has there been any announcements yet?

**Comment by JustinGrote** [comment]
@theoddler https://devblogs.microsoft.com/cosmosdb/

**Comment by pieterdv** [comment]
there's an early public preview available it seems: https://www.youtube.com/watch?v=NUfK6n8UXi8 and https://gist.github.com/StefArroyo/86a87056300fa58c2042e84cdfaa0e1c#file-azurecosmosdblinuxemulatorgist-md unfortunately not working on M1 macs, so not able to test myself, hope support for M1 is coming soon(ish)

**Comment by koprivajakub** [comment]
M1 support is kind of must have for me. Do you have any timeline when this can be expected? arm64 is here for at least a year now. And not to mention that there won't be a single Mac without arm64 architecture in few years.

**Comment by milismsft** [comment]
@koprivajakub @pieterdv, please refer to https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=ssl-netstd21 for Cosmos DB related MacOS and Linux support.
We do not have a timeline currently regarding the Cosmos DB emulator running on M1/M1 Pro Apple silicon based chip. There are tough challenges ahead that might require a rewrite of significant parts of the emulator code, since currently our binaries are X64 based ones and require an Intel chip.

**Comment by CharlieDigital** [comment]
@milismsft does the team have any insight into why the emulator image doesn't work on M1 Macs even with docker even with Rosetta?  It's very unfortunate.  I know that the serverless option is quite cheap for development use cases, but it would be nice to also have a local option to work with.

**Comment by milismsft** [comment]
@CharlieDigital The Cosmos DB emulator Docker image for Linux requires a x64 compatible CPU. M1 is an arm64 based CPU.

**Comment by CharlieDigital** [comment]
Understood, but there are other x64 images that work on M1 under emulation via Rosetta.

**Comment by javierholguera** [comment]
@CharlieDigital would this approach work? https://forums.docker.com/t/run-x86-intel-and-arm-based-images-on-apple-silicon-m1-macs/117123

> The default, of course, is to run the ARM version but if you use the --platform linux/amd64 parameter Docker will run the Intel version for you.

I don't have a Mac with an M1 to test but have been considering getting one and would be interested to see if this fixes it with Cosmos.

**Comment by CharlieDigital** [comment]
@javierholguera unfortunately, it does not work (tried it when I first got my MBP M1) and that is what makes it puzzling from a technical perspective; I'm very curious why the emulation doesn't work for this image.

```
docker run --rm -it --platform linux/amd64 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
./palrun: ERROR: Invalid mapping of address 0x40037dd000 in reserved address space below 0x400000000000. Possible causes:
1) the process (itself, or via a wrapper) starts-up its own running environment sets the stack size limit to unlimited via syscall setrlimit(2);
2) the process (itself, or via a wrapper) adjusts its own execution domain and flag the system its legacy personality via syscall personality(2);
3) sysadmin deliberately sets the system to run on legacy VA layout mode by adjusting a sysctl knob vm.legacy_va_layout.
```
![cosmos-docker](https://user-images.githubusercontent.com/779970/157716041-8df32ff2-7ed6-4c22-a225-ff612b8df7c0.gif)

**Comment by growthvision** [comment]
2022, June.. What about image for M1?

**Comment by BenjaBobs** [comment]
Also, any news on gremlin support?

**Comment by ramzzzay** [comment]
September 2022 -- any news?

**Comment by daveHylde** [comment]
I've created this feedback post regarding arm64 support for the emulator (or docker image). Upvote if you agree.

https://feedback.azure.com/d365community/idea/dc98013b-7348-ed11-a81b-000d3ae3db6e

**Comment by Aravin** [comment]
Any update?

**Comment by bladelson** [comment]
Any update?

**Comment by MrDizzle** [comment]
Any update for this please?

**Comment by JustinGrote** [comment]
> Any update for this please?
When someone just asked two days ago, it's bad form to ask yet again right after, all you're doing is polluting people's notifications.

**Comment by MrDizzle** [comment]
> > Any update for this please?
> 
> @MrDizzle When someone just asked two days ago, it's bad form to ask yet again right after, all you're doing is polluting people's notifications.

Wait isn't that what you are doing right now by chastising me? 😅

**Comment by thesqlpro** [comment]
For now, if you can't get the emulator to work with the docker container then use the free tier:
https://learn.microsoft.com/en-us/azure/cosmos-db/free-tier

Cosmos DB is a PaaS service as such it is designed for the cloud.  Hard to emulate all that on a personal computer, however I understand the need for testing/training/learning on something local. Not an answer, just a suggestion that might help on your Cosmos journey.

**Comment by CharlieDigital** [comment]
@thesqlpro I disagree that it's hard to emulate.

- [DynamoDB has a local downloadable runtime and a Docker image that works on Arm64](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)
- [Google Firestore is part of the Firebase emulator suite and works great!](https://firebase.google.com/docs/emulator-suite) (I've personally switched to Firestore)
- [LocalStack emulates most of the AWS stack](https://localstack.cloud/) (I use this at work where we use it to emulate SNS/SQS locally, but it can emulate a whole swath of AWS services with high fidelity)

I don't understand the reasoning why Microsoft can't make this work or is choosing not to make this work.  My guess is that the emulator or the core engine itself has some incompatible C/C++ dependencies which is why the x64 emulation doesn't work on Arm64.

That said, I recently came across an emulator built by Vercel of all companies.

https://github.com/vercel/cosmosdb-server

Not sure how well it works nor how compatible it is with the current CosmosDB API, but I would encourage folks to take a look.

**Comment by Socolin** [comment]
> Not sure how well it works nor how compatible it is with the current CosmosDB API, but I would encourage folks to take a look.

Last time I checked when using Linq it throw an error https://github.com/vercel/cosmosdb-server/issues/59 and there is no commit since May, so I'm not sure this alternative is usable.
Also the linux image already available is very buggy (stop working after some times, with 1 cpu using 100%) , so don't get too much hope in the M1 version if MS don't address other problems, and so far I got no response to my bugs reports
