### ISSUE TITLE
Running with Azure Storage Emulator

### ISSUE THREAD

**Issue by KevinMcDonnell-BC** [Azure/azure-cosmos-db-emulator-docker#20]
Is it possible to use the Azure Storage Emulator to hold the Web Jobs with this? It looks like the config for AzureWebJobsStorage either allow local dev (assuming installed on the running device) or in Azure. The connection string I have tried is below and using the Storage Emulator in Docker from https://github.com/tg123/Docker-AzureStorageEmulator. Be great to be able to merge this.

"AzureWebJobsStorage": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;TableEndpoint=http://localhost:10001/devstoreaccount1;QueueEndpoint=http://localhost:10002/devstoreaccount1;",
    "AzureWebJobsDashboard": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;TableEndpoint=http://localhost:10001/devstoreaccount1;QueueEndpoint=http://localhost:10002/devstoreaccount1;",

**Comment by tjrobinson** [comment]
@KevinMcDonnell-BC This is the repository for the Azure Cosmos DB Emulator which as far as I know has no direct relevance to the Azure Storage Emulator or WebJobs. Unless I've missed something, I think this issue belongs in https://github.com/Azure/azure-storage-net/issues?

To answer your question however, the Azure Storage Emulator docker image can be used instead of the local emulator, or running in Azure itself. However, it's not been updated for a while and doesn't work with the latest versions of the nuget packages, see: https://github.com/Azure/azure-storage-net/issues/708

**Comment by KevinMcDonnell-BC** [comment]
No, this is about using the Azure Cosmos DB Emulator in Docker but using another Docker container running the Azure Storage Emulator to provide the storage for the web jobs. The issue is that the Cosmos Emulator config only allows you to say local storage or an Azure Storage key. Be great if you could pass the full Connection String and then could use a local storage emulator container for the web jobs. Does that make more sense?

**Comment by tjrobinson** [comment]
@KevinMcDonnell-BC Ah ok. The bit I'm still confused about in that case is where WebJobs fits into this? Where in the Cosmos DB Emulator does it let you configure any WebJob settings? Are you talking about the trigger configuration for the WebJob?

**Comment by KevinMcDonnell-BC** [comment]
Had to go back and check what I was trying to do and I think I'm confusing myself too! The WebJobs are about the triggers for Azure Functions run locally. I was trying to merge the Cosmos Emulator and Azure Storage Emulator in to a single Docker file and was hitting an issue with the storage strings but I can't for the life of me find out where it is.

Happy to close this off.

**Comment by tg123** [comment]
I will update microsoft docker image for storage emulator to latest version

**Comment by KevinMcDonnell-BC** [comment]
Closing as per comment above
