### ISSUE TITLE
Expose gremlin support

### ISSUE THREAD

**Issue by MrGaribaldi** [Azure/azure-cosmos-db-emulator-docker#31]
Since the emulator now supports connecting with the gremlin API, it would be nice if this is somehow exposed, either by default or if an environment variable is set.

A guide for how to do it with a local install can be found here https://github.com/MichalWierzbinski/cosmosdb-emulator-gremlin though that won't work with the current docker image since we can't pass arguments to it.

**Comment by davidOSUL** [comment]
Can't this be done by setting AZURE_COSMOS_EMULATOR_GREMLIN_ENDPOINT=true within the container as described here: https://hub.docker.com/r/microsoft/azure-cosmosdb-emulator/ ?

**Comment by danielcweber** [comment]
I strongly suspect that setting the AZURE_COSMOS_EMULATOR_GREMLIN_ENDPOINT environment variable ceased to work on some recent version of the emulator.

The [Github action](https://github.com/southpolesteve/cosmos-emulator-github-action) stopped working for me, also I can't connect locally although the variable is set system-wide (and has been for quite a while).

**Comment by sajeetharan** [comment]
https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/59 Closing as a duplicate
