### ISSUE TITLE
Image doesn't run on windows server 2019 docker

### ISSUE THREAD

**Issue by Nixes** [Azure/azure-cosmos-db-emulator-docker#32]
Tried to run this image on windows server 2019 in Azure and received:

```
docker pull microsoft/azure-cosmosdb-emulator

C:\Program Files\Docker\docker.exe: Error response from daemon: CreateComputeSystem d78c0667603b0fa05a008d65f06b59fbd93eceb4f26a349498df3f5d66615390: The container operating system does not match the host operating system.
(extra info: {"SystemType":"Container","Name":"d78c0667603b0fa05a008d65f06b59fbd93eceb4f26a349498df3f5d66615390","Owner":"docker","VolumePath":"\\\\?\\Volume{fd39e1ff-86a8-4edc-bdf3-43a68fbcff28}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\d78c0667603b0fa05a008d65f06b59fbd93eceb4f26a349498df3f5d66615390","Layers":[{"ID":"e703197d-7eb6-516c-9c8e-ee8277d36299","Path":"C:\\ProgramData\\docker\\windowsfilter\\a54a085f0171eb62a5e6283e1a718a140744709741890380712abdde99879a04"},{"ID":"96c0f581-b443-57f3-9a91-2fb9dc335b98","Path":"C:\\ProgramData\\docker\\windowsfilter\\63556e8392e32864b635c34a4845c3f5488f3d178a515c258b1aac9e12b8c576"},{"ID":"e73eeb53-762e-51bf-a2a5-8413bd57c1f3","Path":"C:\\ProgramData\\docker\\windowsfilter\\2e05f190b6d00e60db94463636957b1e8b9948f9a86bcd185e2e085a9547a190"},{"ID":"522af03d-ca75-566a-a33a-9da0b3ad35da","Path":"C:\\ProgramData\\docker\\windowsfilter\\1a307c4d49ed20f9a2c45d7ef23f5f76675e54eacb5241b6e765f01c28bab275"},{"ID":"35488ffd-95b6-5d50-a61f-54d28c5918b4","Path":"C:\\ProgramData\\docker\\windowsfilter\\192b7d18bb06717da5791104e90b202fce56c821b9fbf5c81c9b61094b3cfe62"},{"ID":"6c23280e-815d-5675-abc9-a7573e57286e","Path":"C:\\ProgramData\\docker\\windowsfilter\\11122141f17ccbe5d96a1af7c4cb0518776f2bb8533c0d89b1d895e08f73a179"},{"ID":"d4ae93bf-fe12-5cbf-a1d0-8409575739b4","Path":"C:\\ProgramData\\docker\\windowsfilter\\7ae8a8f0a112b3978170a2c62d8ac856f711a93aa14b46be642890024d7ce083"},{"ID":"2e9c5c7d-0775-53c8-80c5-f66513ca4aa9","Path":"C:\\ProgramData\\docker\\windowsfilter\\3473a5af443d9925ab51c89ef6dfe39c0a6f509baff1a7997452af5d68de8166"},{"ID":"5de1c788-d71b-5e9a-b246-7a0c484277f5","Path":"C:\\ProgramData\\docker\\windowsfilter\\f406143b1a024901ae9382e0fe59d61965e097a9ef5974204149dfff9e850d6a"},{"ID":"bb57300d-edb4-5ba5-b1a9-16f07cb66100","Path":"C:\\ProgramData\\docker\\windowsfilter\\3bd5d64675da336dfb59e50151646cb8e691faf5bbc977d19192c9205bdd156c"},{"ID":"f2e4fde9-ca9b-5821-a9c4-a01edd9aa269","Path":"C:\\ProgramData\\docker\\windowsfilter\\01e41ea7fdb63c8c1b0558d1159fc9b8c7b957b2a780fb13c0ca048dfe3a926b"},{"ID":"3069bb7f-f69d-53af-9a3e-441aa2986036","Path":"C:\\ProgramData\\docker\\windowsfilter\\42e6331c13fae9de3728a473b47cb250d5f603f63f2e02c09e55d3e51e7493ef"}],"MemoryMaximumInMB":2048,"HostName":"d78c0667603b","MappedDirectories":[{"HostPath":"C:\\Users\\kepleradmin\\AppData\\Local\\CosmosDBEmulator\\bind-mount","ContainerPath":"C:\\CosmosDB.Emulator\\bind-mount","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"EndpointList":["1C770668-47E9-40A2-9451-1DE96A034ADB"],"AllowUnqualifiedDNSQuery":true}).
```

I would guess the image needs to be rebuilt to support the latest windows server OS?

**Comment by chrislangston** [comment]
What is the status of this issue?  We’d like to wire in Integration testing during our CI/CD Azure pipeline process and this is not working.

**Comment by clawrenceks** [comment]
It would be hugely beneficial if a version of this image for 1903 based containers could be created. This would allow running on Server 2019 and would also remove the need for the huge 6GB container size currently seen because the image is based on the original windowsservercore (server 2016) image.

For now I have built my own version of an image that will run on server 2019, based on the Dockerfile from the repository, but it would be much better if a Microsoft provided image could be provided.

If anybody wants the Dockerfile that I am using to run this on server 2019 based on the 1903 images, just let me know.

**Comment by aaronscribner** [comment]
@clawrenceks I would greatly appreciate the image.

**Comment by chrislangston** [comment]
@clawrenceks   Hi Chris I'd like a copy of your Dockerfile.  How large is your image and how long does it take for everything to get downloaded and available?

**Comment by EricDahlvang** [comment]
In serious need of a HostedVS2019 container.  Is there a workitem for this?

Lots of others asking for the same thing: https://marketplace.visualstudio.com/items?itemName=azure-cosmosdb.emulator-public-preview&ssr=false#qna

**Comment by EricDahlvang** [comment]
Just found out the emulator is installed by default on 2019 hosts.  This script will start it:

```ps
Write-Host "Starting Comsos DB Emulator" -ForegroundColor green 
Start-Process "C:\Program Files\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe" "/NoExplorer /NoUI /DisableRateLimiting /PartitionCount=100 /Consistency=Strong /enableRio /overrides=sqlAllowGroupByClause:true;enableDefaultIndexEncodingOptions:true" -Verb RunAs
Import-Module "C:\Program Files\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
Get-Item env:* | Sort-Object -Property Name
for ($i=0; $i -lt 10; $i++) {
  $status=Get-CosmosDbEmulatorStatus
  if ($status -ne "Running") {
    sleep 30;
    Write-Host "Cosmos DB Emulator Status: $status" -ForegroundColor yellow
  } else {
  break;
  }
}
```

This doesn't help those who are trying to run different tests on different cosmos containers, but might unblock some.

**Comment by ankku** [comment]
> Just found out the emulator is installed by default on 2019 hosts. This script will start it:
> 
> ```postscript
>    Write-Host "Starting CosmosDB Emulator"
>    Import-Module "C:/Program Files/Azure Cosmos DB Emulator/PSModules/Microsoft.Azure.CosmosDB.Emulator"
>    Start-CosmosDbEmulator
> ```
> 
> This doesn't help those who are trying to run different tests on different cosmos containers, but might unblock some.

I tried this and after this Powershell task added the Cosmos Db Emulator tasks from the market place in my Yaml pipeline but I get error as host os does not match container os. How did you test the cases with Emulator? Did it work?

**Comment by brasky** [comment]
This took me over a day of struggle to find out, we are on .net 6 and luckily server 2022 also has cosmos db emulator pre-installed. 

These docs are so unclear... https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-setup-ci-cd


Thank you @EricDahlvang !
