### ISSUE TITLE
Pull docker image on Mac OS

### ISSUE THREAD

**Issue by wm-048** [Azure/azure-cosmos-db-emulator-docker#34]
Just wondering is there any way to get docker image of cosmos DB and bring up a container service for it on Mac OS? Asking because we were using remote cosmos DB for dev before, but we have to build our project in local now for test purpose. In our case MacOS is the only choice and no VM is allowed.

**Comment by pseudoramble** [comment]
Just so you're not left hanging - no right now there isn't. Apparently it's being worked on but I think it's taking some time.

https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/13

**Comment by pseudoramble** [comment]
Also https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/17.

**Comment by peterseale-tethr-com** [comment]
From the feedback page: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/18533509-add-documentdb-emulator-support-for-mac-os-x-and

> June 24, 2019
> Just a quick update. Work on this feature continues but is taking longer than expected.
> 
> We have recently published guidance how how users who can run Windows in a VM whether on Parallels or Virtual Box with a Mac or Linux host can use the Cosmos emulator. Please feel free to use this as a workaround.
> https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#running-on-mac-or-linux
> 
> When this feature is complete we will update here.
> 
> Thank you.

I am also eagerly awaiting this, along with the other 1700 votes. So you're not alone.

**Comment by drewschaeffer** [comment]
Wondering if there is any update on this issue. Docs still point to running hypervisor with Windows to use the emulator on MacOS

**Comment by kelong** [comment]
2022 still nothing??

**Comment by niteshvijay1995** [comment]
Linux Emulator is supported in Mac with Intel Chips ([Documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator?tabs=docker-linux%2Ccsharp&pivots=api-nosql))

Work is in progress to support emulator natively on Mac with M1/2/3 chips.
