### ISSUE TITLE
Unable to create a collection

### ISSUE THREAD

**Issue by dArignac** [Azure/azure-cosmos-db-emulator-docker#35]
Hi,

I setup the Cosmos DB Emulator on Docker for Windows with the intend to use it for Graph database with Gremlin API.

According to the docs I shall create a database and a collection, see [here](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#gremlin-api).
However, I cannot create a collection, only databases and containers, which results only in SQL databases as far as I understand:

![image](https://user-images.githubusercontent.com/106409/68463566-3b3f7180-020f-11ea-8a7d-7b0ac80ab515.png)

How can I solve this? Makes the emulator pretty useless for my case.
Issue may be related to #7 

Thanks!

**Comment by sajeetharan** [comment]
https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/59 Closing it as a duplicate
