### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by jabba2324** [Azure/azure-cosmos-db-emulator-docker#37]
Hi

Is there any plan to support Linux for the emulator, its a very useful tool for writing integration tests and CI/CD pipelines. For devs that aren't just tinkering around the simulator has almost no value.

**Comment by Adebeer** [comment]
Agree. I would love to have this working on Docker linux containers.

I've just setup a new PC and, from past experience I've had a lot of issues getting the emulator to work on windows - so I thought sweet, lets use Docker - and it works great

And then Azurite came along - I thought sweet, I'll use that in docker too...

But alas - Azurite only supports Linux Docker containers... so I can't run both (and, well we use both CosmosDB and Azure blob storage on our projects)

All in all, I'm a sad kitty :(

**Comment by vhendriks81** [comment]
Would love linux support as well although it IS possible to run linux and windows containers side-by-side (@Adebeer ). With Docker Desktop you can switch between windows or linux containers but that only switches which type you're managing. It doesn't stop the running containers..

**Comment by Adebeer** [comment]
@vhendriks81 I did not know that - thanks for the tip! 👍

**Comment by cdesewell** [comment]
@vhendriks81 I'm talking about running on a Linux host such as a build agent or even a server, not a docker container inside Windows. I've tried running this in Wine and gotten somewhat far (not working well enough though), the simulator seems to be mostly dot-net based so some of the some should already be cross-platform, would be good to get a native port though.

**Comment by jabba2324** [comment]
Any update on this?

**Comment by jabba2324** [comment]
Looks like its coming this year: https://twitter.com/markjbrown/status/1369322324072132608

**Comment by sajeetharan** [comment]
This is in public preview https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator

**Comment by BenjaBobs** [comment]
Any news of Gremlin API support?

**Comment by sajeetharan** [comment]
@BenjaBobs It's on the way https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/19636633-support-gremlin-apis-on-cosmos-db-emulator

**Comment by BenjaBobs** [comment]
@sajeetharan went to check the status today, and it seems the link gives a 404.
Any news on gremlin support?

**Comment by sajeetharan** [comment]
@manishmsfte

**Comment by thomasouvre** [comment]
Is there any updates ? The support of Gremlin API in linux container would be great !

**Comment by BenjaBobs** [comment]
It's been almost a year. Any news? @sajeetharan @manishmsfte

**Comment by boginw** [comment]
@sajeetharan should we consider the closing of this issue as Gremlin support will not be implemented?

**Comment by sajeetharan** [comment]
@boginw Yes as of now there are no plans to add this support. However, there is a duplicate issue on the same, we will keep that for tracking!

**Comment by BenjaBobs** [comment]
> @boginw Yes as of now there are no plans to add this support. However, there is a duplicate issue on the same, we will keep that for tracking!

How can we voice our opinion that we want this feature in a way that it gets seen by the necesary eyes, and also doesn't end up 404'ing?
