### ISSUE TITLE
Running Emulator gives Starting Emulator and nothing else

### ISSUE THREAD

**Issue by sudsy** [Azure/azure-cosmos-db-emulator-docker#4]
When I run the command:

`docker run -v %LOCALAPPDATA%\CosmosDBEmulatorCert:c:\CosmosDBEmulator\CosmosDBEmulatorCert -P -t -i microsoft/azure-cosmosdb-emulator`

I get:

`Starting Emulator`

after waiting about 3 minutes or so for further output, the process exits.

I checked %LOCALAPPDATA%\CosmosDBEmulatorCert and the folder is empty.

Any ideas?

**Comment by grahamehorner** [comment]
@sudsy what amount of memory have you allocated to docker on you hosting machine, I've found that 4gb is needed for most windowsservercore based images :'( hence why I would like to see a nanoserver image ;)
