### ISSUE TITLE
How do I change the PartitionCount

### ISSUE THREAD

**Issue by shawndewet** [Azure/azure-cosmos-db-emulator-docker#41]
When running in docker, it applies the standard 25-container limit.
How do I change my docker run command to increase this container limit?

**Comment by lucax88x** [comment]
by passing AZURE_COSMOS_EMULATOR_PARTITION_COUNT as environment variable

**Comment by krist55555** [comment]
Same questions. How can we change the PartitionCount? I tried to change the Startemu.cms and add the partition count attibute. But I cannot build image with all the other filed unchanged. 
![image](https://github.com/Azure/azure-cosmos-db-emulator-docker/assets/136840267/6c074683-1df1-43cd-9d1d-f9a2127952c5)

**Comment by kerryjiang** [comment]
Add this environment variable:
-e AZURE_COSMOS_EMULATOR_START_PARTITIONCOUNT=100

**Comment by sajeetharan** [comment]
Hope the above suggestion helped.
