### ISSUE TITLE
Unable to skip SSL authentication when connecting to Emulator running in Linux Docker Container

### ISSUE THREAD

**Issue by davidguidali** [Azure/azure-cosmos-db-emulator-docker#43]
Hi there
I am developing a C# .NET Core app (on windows) and want to connect to the cosmos emulator running in a linux docker container on docker desktop for windows. I don't want to use SSL authentication so I try to make use of the most recent CosmosClient of Microsoft.Azure.Cosmos package. However, this doesn't seem to work.

Steps to reproduce:

On a windows machine, pull the most recent image of the cosmos emulator

`docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator`

Start up a new emulator container 

`docker run -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254  -m 3g --cpus=2.0 --name=test-linux-emulator -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true -it mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator`

Navigate to _https://localhost:8081/_explorer/index.html_ and download the sample app for C# .NET Core.

Open the sample app in Visual Studio and update the Nuget package _Microsoft.Azure.Cosmos_ to Version 3.20.1.

Open the class Program.cs and change the method _GetStartedDemoAsync_ to skip SSL authentication:

 ```
public async Task GetStartedDemoAsync()
{
    CosmosClientOptions cosmosClientOptions = new CosmosClientOptions()
    {
        HttpClientFactory = () =>
        {
            HttpMessageHandler httpMessageHandler = new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            };
            return new HttpClient(httpMessageHandler);
        },
        ConnectionMode = ConnectionMode.Gateway
    };

    // Create a new instance of the Cosmos Client
    this.cosmosClient = new CosmosClient(EndpointUri, PrimaryKey, cosmosClientOptions);
    await this.CreateDatabaseAsync();
    await this.CreateContainerAsync();
    await this.ScaleContainerAsync();
    await this.AddItemsToContainerAsync();
    await this.QueryItemsAsync();
    await this.ReplaceFamilyItemAsync();
    await this.DeleteFamilyItemAsync();
    await this.DeleteDatabaseAndCleanupAsync();
}
```

Then hit F5 to run the program. 

**Expected result**
The program runs successfully.

**Actual result**
The program hangs in _this.CreateDatabaseAsync();_, never returning and never creating a database.

**Comment by sogustavo** [comment]
Same problem here

**Comment by AdamBremholm** [comment]
same problem here. Did you find some workaround?

**Comment by alexanderbikk** [comment]
@davidguidali I'm getting exactly the same problem here. I'm running ComsosDb emulator in Linux Docker Container on Docker for Windows. And try to connect from .net 6 application. 
If I don't use workaround for ssl certification I'm getting excepted connection issue. When I try to use recommended workaround The program hangs in first call to CosmosDb. 

Didn't you find a solution?

**Comment by milismsft** [comment]
@davidguidali @sogustavo @AdamBremholm please refer to https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=ssl-netstd21, in particular step 1 and 3 (see "-e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr"). In your .NET or Java client app you must configure the Cosmos DB endpoint to use that IP address setting and not "localhost". For .NET applications please also follow https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21#linux-environment to ensure the emulator's self signed certificate is properly added to your host configuration (the .PEM file downloaded per first link can be used as the .CRT file in the second link).
