### ISSUE TITLE
Not able to pull collections in Web View

### ISSUE THREAD

**Issue by shelwig** [Azure/azure-cosmos-db-emulator-docker#5]
I am able to navigate to the emulator web portal, however, it fails when trying to retrieve collections. I am receiving the following errors: 

Failed to load resource: net::ERR_CONNECTION_REFUSED: localhost:8081/dbs

```
Uncaught TypeError: Cannot read property 'queryDocuments' of undefined
    at Program.refreshCollection (built/Program.js:24)
    at HTMLSpanElement.<anonymous> (externals/knockout.js:89)
    at HTMLSpanElement.dispatch (jquery.js:9)
    at HTMLSpanElement.r.handle (jquery.js:9)
```

I believe this is occurring because when running the emulator in the Docker Container the URL is not localhost. In my case it was running on 172.26.69.202:8081.

**Comment by taishmanov** [comment]
@shelwig look https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/7#issuecomment-356297895

**Comment by sajeetharan** [comment]
Please reopen if you are still facing this issue!
