### ISSUE TITLE
MongoDB API on Linux not working

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [Azure/azure-cosmos-db-emulator-docker#52]
When running the documented docker command found on
https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=mongodb-api%2Cssl-netstd21#run-the-linux-emulator-on-linux-os

docker run \
    --publish 8081:8081 \
    --publish 10251-10254:10251-10254 \
    --memory 3g --cpus=2.0 \
    --name=test-linux-emulator-mongo \
    --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 \
    --env AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true \
    --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr \
    --env AZURE_COSMOS_EMULATOR_ENABLE_MONGODB_ENDPOINT=4.0 \
    --interactive \
    --tty \
    mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

The container just keeps restarting...
Looking at the container logs, I see the following message.

**Invalid endpoint type enabled; only SQL endpoint type is supported.**

I am trying to run the on WSL2 configured for Linux containers.

**Comment by esdrasbeleza** [comment]
Same issue here. I'm trying to run the emulator on macOS using [these instructions](https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=sql-api%2Cssl-netstd21).

**Comment by Pete-PlaytimeSolutions** [comment]
I ended up getting it going by overriding the docker entrypoint with a manual setup...

docker run -d --name=cosmosdb --restart unless-stopped \
    -p $PORT:8081 \
    -p 10251:10251 \
    -p 10252:10252 \
    -p 10253:10253 \
    -p 10254:10254 \
    -p 10255:10255 \
    -m 2g --cpus 2.0 \
    -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5 \
    -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true \
    -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr \
    -e ENABLE_MONGODB_ENDPOINT=4.0 \
    mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator \
    /usr/local/bin/cosmos/start.sh /EnableMongoDbEndpoint=4.0 /MongoPort=10255 /Key:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==

**Comment by sajeetharan** [comment]
This has been addressed with the last release, can you please check the latest image and reopen if you are still facing the issue

**Comment by postcode-ai** [comment]
@sajeetharan - do you have any instructions on EXACTLY how to get the cosmos emulator working with mongodb api on a mac? Despite following loads of "fixes" all over the place I can only get the emulator running with SQL API.
