### ISSUE TITLE
 ServiceUnavailable  (503); Substatus: 20003

### ISSUE THREAD

**Issue by Burgyn** [Azure/azure-cosmos-db-emulator-docker#63]
Hi guys,

First of all, I want to thank you for the emulator and your work on it 👍

We use this emulator in our temporary Kubernetes environments for integration tests. (_A Kubernetes cluster/AKS is created, pods created, services are deployed, integration tests are run, and the environment is dropped. All this in the Pull Request process - CI)_

Unfortunately, it sometimes happens that the integration tests for one of our services that connect to this emulator fail. The only thing we can detect is that we get an exception: `Microsoft.Azure.Cosmos.CosmosException: Response status code does not indicate success: ServiceUnavailable(503); Substatus: 20003; ActivityId: a4851255-27a6-4900-979b-4a47746a8cbc; Reason:()`.

The CosmosDb pod does not report any failures.

Unfortunately, we don't know how to proceed, what needs to be found out, and how to solve it. It's unpredictable.

Can you please help us?
Thanks a lot 🙏

**Comment by maranmaran** [comment]
Same thing, I guess it goes over some request count and starts some kind of throttling. We have retry mechanisms implemented so it works out either way but it's annoying as it takes much longer due to exception handling and timeouts.

**Comment by LloydNicholson** [comment]
> Hi, I am using the docker linux image for Cosmos db and I am getting the same error

I found that using the following options fixed the issue for me. Set LimitToEndpoint to true and use Gateway Connection mode.

**Comment by callum-hopkins-dev** [comment]
I found that on my Linux distribution (Fedora Silverblue), and probably most other distributions, the default soft limit on open files was `1024`. It seems that the emulator was hitting this limit almost immediately. My fix was to increase the soft limit to the hard limit. In this case I ran: `ulimit -Sn 524288`. However, please be careful, you should not set your soft limit to a value higher than your hard limit, which can be found by running `ulimit -Hn`.
