### ISSUE TITLE
Invalid endpoint type enabled; only SQL endpoint type is supported.

### ISSUE THREAD

**Issue by jonaswre** [Azure/azure-cosmos-db-emulator-docker#66]
Im having trouble starting a cosmosdb that has a mongodb endpoint enabled. 
Im following this documenation https://learn.microsoft.com/en-us/azure/cosmos-db/docker-emulator-linux?tabs=mongodb-api%2Cssl-netstd21

But when executing step 3. I get `Invalid endpoint type enabled; only SQL endpoint type is supported.` Which seams to be odd...

Running this from the following documenation
```
docker run \
    --publish 8081:8081 \
    --publish 10250-10255:10250-10255 \
    --name=test-linux-emulator-mongo \
    --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 \
    --env AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true \
    --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr \
    --env AZURE_COSMOS_EMULATOR_ENABLE_MONGODB_ENDPOINT=4.0 \
    --interactive \
    --tty \
    mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:mongodb
```
yields this
```
This is an evaluation version.  There are [66] days left in the evaluation period.
Invalid endpoint type enabled; only SQL endpoint type is supported.
```

**Comment by ThaminduDilshan** [comment]
I'm also having the same issue. Ended up with below error.
```
This is an evaluation version.  There are [65] days left in the evaluation period.
Invalid endpoint type enabled; only SQL endpoint type is supported
```

**Comment by jonaswre** [comment]
it would be such a good Azure Functions dev stack when we would be able to use mongodb here... 

Azureite: mcr.microsoft.com/azure-storage/azurite
Azure Functions: mcr.microsoft.com/azure-functions/node:4-node16
CosmosDB: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:mongodb

 And one funny thing 
```mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:mongodb == mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator``` 

There is a mongodb tag but mongodb is not supported?

**Comment by kurumim** [comment]
I'm also having the same issue

**Comment by sajeetharan** [comment]
@kurumim @jonaswre @ThaminduDilshan can you confirm if you are seeing this error with the latest image?
