### ISSUE TITLE
Error response from daemon: manifest for microsoft/azure-cosmosdb-emulator:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by alex-shmyga** [Azure/azure-cosmos-db-emulator-docker#67]
when I try to run `docker pull microsoft/azure-cosmosdb-emulator`
I get `Error response from daemon: manifest for microsoft/azure-cosmosdb-emulator:latest not found: manifest unknown: manifest unknown`

**Comment by MatsMold** [comment]
Try
docker pull mcr.microsoft.com/cosmosdb/windows/azure-cosmos-emulator

**Comment by Jonathanbarry1** [comment]
What did you change?
