### ISSUE TITLE
CosmosDB Explorer Issues

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-cosmos-db-emulator-docker#7]
CosmosDB explorer is no longer showing collections, users, stored procedures etc. the browser shows a single 404 error for https://...:8081/_explorer/externals/bootstrap.min.css.map

**Comment by ransagy** [comment]
I have a similar issue where on startup there are two ERR_CONNECTION_REFUSED on the /dbs endpoint and no data is shown in the explorer, nor any actions are shown (create database, collection etc).

**Comment by taishmanov** [comment]
https://<host>:<port>/_explorer/built/Common/DocumentClientFactory.js file has a bug. 
Line 8: `endpoint = endpoint || "https://localhost:" + location.port;`
I changed it to `endpoint = endpoint || "https://" + window.location.host;`.

Just change this line in browser dev tools or find DocumentClientFactory.js file in your machine and fix it manually. The file's location was for me: "C:\ProgramData\Docker\windowsfilter\3cb46544dcb17d4b41c1334e3dbd06b8315fa07f3a940bf7c654a428f2a955fd\Files\Program Files\Azure Cosmos DB Emulator\Packages\DataExplorer\built\Common"

**Comment by XristophD** [comment]
Thank you for the fix. 
Do I understand this right, that this is not an issue of the docker-container repository but an error within the initial CosmosDB Emulator? Who is maintaining the DocumentClientFactory.js file?
