### ISSUE TITLE
Error response from daemon: manifest for microsoft/azure-cosmosdb-emulator:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by Funshinho** [Azure/azure-cosmos-db-emulator-docker#80]
**Describe the bug**
An error occurs when trying to pull image

**To Reproduce**
Run `docker pull microsoft/azure-cosmosdb-emulator`

**Expected behavior**
The image is pulled correctly

**Desktop (please complete the following information):**
 - OS: Windows

**Docker Images Used: **
 - Windows

**Comment by sajeetharan** [comment]
You need to use` docker pull mcr.microsoft.com/cosmosdb/windows/azure-cosmos-emulator` , we will update the doc accordingly.
