### ISSUE TITLE
Container starts and immediately stops on macOS

### ISSUE THREAD

**Issue by LeonardoBonacci** [Azure/azure-cosmos-db-emulator-docker#81]
Using 
- Mac Sonoma 14.1.1
- Docker v4.25.2

Following the instruction [here](https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator?pivots=api-nosql&tabs=docker-linux%2Ccsharp), executing this command:

```
docker run --platform linux/amd64 \                                                                                          
    --publish 8081:8081 \
    --publish 10250-10255:10250-10255 \
    --interactive \
    --tty \
    mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
```

The container starts, logs the following two lines, and immediately stops.
```
| This is an evaluation version.  There are [158] days left in the evaluation period.
| Starting
exited with code 0
```

**Comment by v1k1** [comment]
Hi @LeonardoBonacci, Running Docker is only supported in OsX, for intel chips. Is your machine on Intel or M1/M2 chipset?

**Comment by replay** [comment]
> Is your machine on Intel or M1/M2 chipset?

I have the same problem, my machine has an M1 chipset

**Comment by sajeetharan** [comment]
Closing this as a duplicate https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/54
