### ISSUE TITLE
Trial expiring soon

### ISSUE THREAD

**Issue by lynkz-matt-psaltis** [Azure/azure-cosmos-db-emulator-docker#92]
Can we please get an updated Linux container image as its due to expire in less than 20 days.

Thanks!

**Comment by sajeetharan** [comment]
Thanks for raising this! sure will keep you posted with the release.

**Comment by mbenabda** [comment]
@sajeetharan Hi there, have you had a chance to take a look at this ? There are [11] days left in the evaluation period.

**Comment by sajeetharan** [comment]
@mbenabda Yes, we are updating the image, and it should be done by early next week. Will keep you posted!
