### ISSUE TITLE
Failed run in Parallels Desktop 19.3 on macbooks with m1, m3 chips

### ISSUE THREAD

**Issue by wondertalik** [Azure/azure-cosmos-db-emulator-docker#99]
**Describe the bug**
I have two macbooks pro with m1 and m3 chips and i can't run an emulator inside atheParallels Dekstop 19.3 with windows 11

**To Reproduce**
1. Install Parallels Desktop 19.3
2. Download and install [emulator](https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator?tabs=windows%2Ccsharp&pivots=api-nosql) using `Windows(locla) manual.
3. Run and in 10-15 sec shows an error.

**Screenshots**
![image](https://github.com/Azure/azure-cosmos-db-emulator-docker/assets/1611064/a5d6cfcf-cf1d-4b6f-9267-1b31059c7f99)

In events i found this

```text
Faulting application name: Microsoft.Azure.Cosmos.Server.exe, version: 2.14.0.0, time stamp: 0x66445983
Faulting module name: Microsoft.Azure.Cosmos.Server.exe, version: 2.14.0.0, time stamp: 0x66445983
Exception code: 0xc000001d
Fault offset: 0x000000000001b760
Faulting process id: 0x0xBD8
Faulting application start time: 0x0x1DAAD306D79173E
Faulting application path: C:\Program Files\Azure Cosmos DB Emulator\Packages\ServerService\ServerService.Code\Microsoft.Azure.Cosmos.Server.exe
Faulting module path: C:\Program Files\Azure Cosmos DB Emulator\Packages\ServerService\ServerService.Code\Microsoft.Azure.Cosmos.Server.exe
Report Id: 0ef7392a-ca63-44ea-a0ad-99205911359c
Faulting package full name: 
Faulting package-relative application ID: 
```

```text
Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program Azure Cosmos Master Service because of this error.

Program: Azure Cosmos Master Service
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 0x0
Disk type: 0x0
```

**Desktop (please complete the following information):**
 - OS: windows 11 enterprise 23H2
 - Parallels Destkop 19.3.1 (54941)
 - Microsoft Cosmo Db Emulator 2.14.17.0

**Arguments && Environment variables to start Docker:
 
**Docker Environment**
 - Docker compose
 - Standalone
 - Others (Please specify)
 
**Additional context**

**Comment by andyvanosdale** [comment]
What architecture is the Windows install? If you try to emulate x86 (it will be slower) and use a Windows x86 install, does it work?

**Comment by wondertalik** [comment]
> What architecture is the Windows install?

```text
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎5/‎14/‎2024
OS build	22631.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

Processor	Apple Silicon   3.20 GHz  (4 processors)
Installed RAM	8.00 GB
System type	64-bit operating system, ARM-based processor
```

>If you try to emulate x86 (it will be slower) and use a Windows x86 install, does it work?

What do you mean?

**Comment by ivanball-hitachi** [comment]
[wondertalik] Were you able to figure it out? A member on my team also have the same issue.

**Comment by wondertalik** [comment]
> [wondertalik] Were you able to figure it out? A member on my team also have the same issue.

Nop and i tried with Parallel Desktop 19.4 with [Using Rosetta to run x86-64 Docker Containers and Binaries in Linux virtual machines with Parallels Desktop](https://kb.parallels.com/129871) and it failed too unfortunatelly.

**Comment by pikami** [comment]
@wondertalik I've been developing a cosmos emulator from scratch, it's not 100% compatible, but it works on my Mac M2 (should work on other cpus as well).
If you're using the cosmos NoSql api you can try it here https://github.com/pikami/cosmium

**Comment by thales-man** [comment]
Win Get is your friend… 
Worked for me on an M1 Pro using VMWare. 
But I'm stunned this product has so many repeating issues in working on its own operating system. I tried everything to get this thing going using v2.14.18, including the expelling numerous unrepeatable incantations to no avail. The Microsoft documentation is sorely lacking and out of date as is the product.

```winget install Microsoft.Azure.CosmosEmulator -v 2.14.16```

**Comment by CSharpFiasco** [comment]
Seems related to https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/54

**Comment by sajeetharan** [comment]
Hi @CSharpFiasco thanks, we are trying to fix this! we will provide an update asap!

**Comment by niteshvijay1995** [comment]
The support for Parallels Desktop on MacOS is restored in version 2.14.20.
Native support using docker containers on Mac with M1/2/3 chips is work in progress.

**Comment by wondertalik** [comment]
> The support for Parallels Desktop on MacOS is restored in version 2.14.20. Use link (https://aka.ms/cosmosdb-emulator) to get latest version of emulator. Native support using docker containers on Mac with M1/2/3 chips is work in progress.

Hello, @niteshvijay1995. Removed and installed and still facing the same problem.

![image](https://github.com/user-attachments/assets/489a8259-2e10-4669-be33-0c44f364a805)


Parallels Desktop 19.4.1 (54985)

**Comment by wondertalik** [comment]
@niteshvijay1995 here there are

[CrashDumps.zip](https://github.com/user-attachments/files/16836480/CrashDumps.zip)

**Comment by niteshvijay1995** [comment]
@wondertalik can you delete this folder and restart emulator to capture new crash dumps?

**Comment by niteshvijay1995** [comment]
@wondertalik, also try a fresh install by manually deleting Emulator binaries from `C:\Program Files` and also from %LOCALAPPDATA%

**Comment by niteshvijay1995** [comment]
> > @wondertalik can you delete this folder and restart emulator to capture new crash dumps?
> 
> [CrashDumps (2).zip](https://github.com/user-attachments/files/16837169/CrashDumps.2.zip)

Is this the only dump captured during the run?

**Comment by wondertalik** [comment]
> Is this the only dump captured during the run?

Yes. And then i tryied fresh install

> @wondertalik, also try a fresh install by manually deleting Emulator binaries from `C:\Program Files` and also from %LOCALAPPDATA%

After fresh install it looks like it works.

![image](https://github.com/user-attachments/assets/cb66bd6e-c093-4365-8516-7ad0d8176b3f)
